image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew
  - java -jar ./artifacts/app-order.jar &

build_script:
  - ./gradlew -Dselenide.headless=true test --info
